id: P000588
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6136
  title: འཛམ་གླིང་འཁྲུག་ཆེན་གཉིས་པ།
  author: ''
  volumes:
    3bbb18c9849e483a805754695ef954d8:
      image_group_id: I1KG8453
      title: ''
      volume_number: 1
      total_pages: 494
